<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>

		<PackageId>Dreamine.PLC.Wpf</PackageId>
		<Version>1.0.0</Version>
		<Authors>Dreamine Core Team</Authors>
		<Company>Dreamine</Company>
		<Description>WPF monitoring and diagnostic UI components for Dreamine PLC communication.</Description>
		<PackageTags>dreamine;plc;wpf;monitoring;diagnostics;communication;industrial-automation</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/CodeMaru-Dreamine/Dreamine.PLC.Wpf</RepositoryUrl>
		<Title>Dreamine.PLC.Wpf</Title>
		<Copyright>© 2026 Dreamine Core Team. All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/CodeMaru-Dreamine/Dreamine.PLC.FullKit</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="icon.png" Pack="true" PackagePath="\"/>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PLC.Abstractions\Dreamine.PLC.Abstractions.csproj" />
		<ProjectReference Include="..\PLC.Core\Dreamine.PLC.Core.csproj" />
	</ItemGroup>

</Project>
